# -*- coding: utf-8 -*-
"""LVADSUSR161_KRITHIKSRI_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sQIBLX-PuJNic9rob2KOI1kzinKNimA2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#1)load dataset
import pandas as pd
ipl=pd.read_csv('/content/Final Dataset - IPL.csv')
print("The first 5 rows of the dataset:",ipl.head(2))
print("The total number of rows and columns",ipl.shape)
print("The Total number of values in the dataset",ipl.size)
print("The total number of null values in the dataset if exists",ipl.isnull().sum())

#2)Data cleaning
print(ipl.info())
#here we can find the missing value but the data not have missing value so data is consistent
print("The duplicate values:",ipl.duplicated().sum())
#here,there is no duplicate values available in our dataset

#3)Descriptive analysis
print("Descriptive analysis of the dataset:")
print(ipl.describe())
#while take any one of the column from the dataset
#highscore-the average highscore lie in 71 and the minimum is 28 and maximum is 140
#50% of the value in range of 57

#4)data visualization
sns.pairplot(data=ipl)
#diagonal represent the individual variable and other plots represent relationship between the columns

ipl.columns

#5)identifying relationship
#find relationship between toss winner and impact on game winner
plt.scatter(ipl['toss_winner'],ipl['match_winner'])
plt.xticks(rotation=45)
plt.show()

#toss decision impact the match winner or not
#choosing fielding people mostly win the match
win_by_decision=ipl.groupby(['toss_decision']).aggregate({'match_winner':'count'})
print(win_by_decision)
sns.barplot(x=win_by_decision.index, y=win_by_decision['match_winner'],width=0.25,hue=win_by_decision.index)
plt.title("winning prediction by toss decision")
plt.show()

#venue distribution over the mathches
win_by_venue=ipl.groupby(['venue']).aggregate({'match_winner':'count'})
print(win_by_venue)
sns.barplot(x=win_by_venue.index, y=win_by_venue['match_winner'],width=0.5,hue=win_by_venue.index)
plt.title("winning prediction by venue")
plt.xticks(rotation=45)
plt.show()

plt.plot(win_by_venue.index,win_by_venue['match_winner'])
plt.xticks(rotation=45)
plt.show()

#6)outlier detection
#ipl.info()
number=ipl[['first_ings_score','second_ings_score','highscore']]
sns.boxplot(number['first_ings_score'])
#outlier value found below 80 so we can remove it
remove_outlier_first=number[number['first_ings_score']>=100]

#after removing outlier
sns.boxplot(remove_outlier_first['first_ings_score'])

sns.boxplot(number['second_ings_score'])
#outlier found below 100 so remove them and c=visualize it
remove_outlier_sec=number[number['second_ings_score']>=110]

#after removing outlier
sns.boxplot(remove_outlier_sec['second_ings_score'])

sns.boxplot(number['highscore'])
#outlier found above 120
remove_out_high=number[number['highscore']<=120]

#after removing outliers
sns.boxplot(remove_out_high['highscore'])

ipl['venue'].str.split(",")[1]

#7
#most of the matches held at mumbai
print(ipl.groupby('venue')['match_id'].count().nlargest(5))
#distribution of stages in ipl
print(ipl['stage'].value_counts())
#the final won by gujarat
ipl[ipl['stage']=='Final']

#8)player spotlight
print("key player:")
print(ipl['player_of_the_match'].value_counts().nlargest(4))
print("top scorer:")
print(ipl['top_scorer'].value_counts().nlargest(4))
print("best bowler:")
print(ipl['best_bowling'].value_counts().nlargest(4))

#toss winner as match winner
s=ipl[ipl['toss_winner']==ipl['match_winner']]
s['match_winner'].value_counts()
s.shape

#got century in one match
ipl[ipl['highscore']==100]

'''9)data discovery
Insights from the dataset:
  There total 74 matches held with the stages of three as group,playoff and final
  and the final is won by Gujarat teams,where there is playoff will be 3 and that played between gujarat,lucknow and rajasthan
  The impact of toss winner and toss decision is included above and from that we can get the insights about
   choosing fielding team had a better chance of winning the teams than batting
   The toss winner will be the match winner in 36 matches out of the 74 matches so the probability of toss winning
   cannot impact the match winning
   so, the decision of the toss will impact the matches
top performers:
   The above questions compases the top performers as player of the match as kuldeep yadav with the maximum of
   4 times he won the player of the match
   Top scorer is jos buttler and best bowler is chahal who won the most of the times
   The highest score and century got by the top scorer as jos buttler
Venue impact:
   most of the matches held at the mumbai with three stadium in the mumbai town itself
   and the next most played stadium is pune which also has the 13 matches held there also