# -*- coding: utf-8 -*-
"""LVADSUSR161_krithiksri(IA1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qjEz1mkOn_xVOOnsepTP0YVajtYyVeQf

Name:Krithiksri Venkatachalam




Employee id:4369
"""

#lab section 1
#1-commercial property management system
length=int(input("enter length of the area in meters:"))
width=int(input("enter width of the area in metres:"))
area=length*width
if area<=1000:
  print("small area")
elif area>1000 and area<=5000:
  print("medium area")
else:
  print("large area")

#2-integrated health management app
height=int(input("enter your height in meters:"))
weight=int(input("enter weight in kg:"))
bmi=weight/(height*height)
if bmi<0.5:
  print("very thin ,take healthy food to get into normal")
elif bmi>=0.5 and bmi<=1:
  print("average for your age!! keep going!!")
else:
  print("obesity, need to take diet")

#3-educational record system

student_grade={
      "peter":{'grade':"A",'subject':'python'},
      "alan":{'grade':'B','subject':'bigdata'},
      "nova":{'grade':'A+','subject':'english'}
  }


def update(x1):
  student_grade.update(x1)
  return student_grade

def retrieve(k):
  result=student_grade[k]
  return result

x1={"preethi":{"grade":'B',"subject":"machine learning"}}

retrieve_data="peter"

print(update(x1))
print(retrieve(retrieve_data))

#lab section-2
#4-content recommendation engine:
age=int(input("enter your age:"))
if age<=5:
  print("hello, children,you may use cartoon channels")
elif age>=5 and age<=15:
  print("hi teens!!,you may use infotainment channels ")
elif age>15 and age<=30:
  print("hello adult!! get into some interesting genre")
else:
  print("get the senior collections")

#5-promotional email dispatcher
subscriber=[1,2,3,4,5,6,7,8,9,22,44,67]
even_numbered=[]
for i in subscriber:
  if i%2==0:
    even_numbered.append(i)
print(even_numbered)

#6-corporate network security system
d={123,456,789}
user_pwd=int(input("enter the password to open:"))
if user_pwd in d:
  print("login successfully!!")
else:
  print("incorrect password")

#lab-section-3
#7-customer feedback analysis tool
def feedback(x1,x2):
  avg_score=(x1+x2)/2
  if avg_score>5:
    print("need to improve some content")
  elif avg_score>=5 and avg_score<=8:
    print("need to concentrate on some area")
  elif avg_score<=9 and avg_score>=10:
    print("excellent")

user1=int(input("enter the score 1:"))
user2=int(input("enter the score 2:"))
feedback(user1,user2)

#8-content moderation system
def content(vowel):
  s_a=0
  s_e=0
  s_i=0
  s_u=0
  s_o=0
  #print(list(vowel))
  for i in list(vowel):
    if 'a' == i:
      s_a+=1
    elif 'e' == i:
      s_e+=1
    elif 'i' == i:
      s_i+=1
    elif 'o' == i:
      s_o+=1
    elif 'u'== i:
      s_u+=1

  total=s_a+s_e+s_i+s_o+s_u
  print("count of vowels",total)


vowel="she is fantasy"
content(vowel)

#9-automated event reminder
import datetime
when_event=input("enter the timing of the event:")
how_remind=input("enter how to remind the event:")
event=["12:00","13:00","14:00"]
if when_event in event:
  print("scheduled")
else:
  print("not scheduled")

#lab section-4
#10-robust financial calculator
try:
  principal=int(input("enter principal amount:"))
  num_of_year=int(input("enter number of years:"))
  rate=int(input("enter rate of interest:"))
  simple_interest=(principal*num_of_year*rate)/100
  print("simple interest:",simple_interest)
except NameError:
  print("values in calculation not sufficient")

#11-online polling system
data=input("enter data to validate:")
if data=="polling":
  name=input("enter name:")
  if name.isalpha():
    print("validated!!")
  else:
    print("invalid")
  dob=input("enter date of birth:")
  if dob.isalnum():
    print("good carry on!!")
  else:
    print("provide valid data")

#12-scientific data processing tool
try:
  def addition(d1,d2):
    sum=d1+d2
    return sum
  def subtract(d1,d2):
    sub=d1-d2
    return sub
  def division(d1,d2):
    div=d1/d2
    return div
  data1=2
  data2=0
  print(addition(data1,data2))
  print(subtract(data1,data2))
  print(division(data1,data2))
except ZeroDivisionError:
  print("divided by zero!!")

#lab-section-5
#13)automated reporting system
log_file=open("log_file.txt",'x')
log_write=open("log_file.txt",'w')
up_time="mostly the uptime between morning nine to evening five"
log_write.write(up_time)
log_write.close()

#14-corporate compliance review tool
log_read=open("log_file.txt",'r')
log_read.read()

#15-dynamic content creation engine
log_update=open("log_file.txt",'a')
updated_time="sometime the server down in weekends"
log_update.write(updated_time)
log_update.write("company holds lot of share compared than last quarter")
log_update.close()
l_read=open("log_file.txt",'r')
l_read.readlines()

